### ISSUE TITLE
Add link to repo in README

### ISSUE THREAD

**Issue by Antoine-lb** [Thomas-McKanna/Files2Prompt#11]
Hello 👋 amazing plugin, I left a review in the vscode store.

I think you should put the link to the repo on the README bc when viewing the plugin from VSCode, the button "Repository" is kind of hidden, is not obvious that the plugin is open source.

Node: I post it on Reddit too (https://www.reddit.com/r/programming/comments/1hf5jf0/vscode_extention_to_copy_multiple_files_for/)

**Comment by Thomas-McKanna** [comment]
Thank you very much for helping to spread the word about this project. I can add a link to the repo in the readme.

Just as a side note - I originally chose XML for the output since I had read somewhere that XML prompts perform well, but other formats are probably not far behind. I could see an addition to this plugin wherein you can choose the output format via a plugin setting.

But, the plugin is also able to parse XML to update file contents (see bottom of readme). This feature _really_ speeds up development for me and I believe it would be harder for this feature to work in Markdown format (since there are already many open source XML parsers, but I'm not sure if the same support exists for parsing Markdown as easily).

**Comment by Antoine-lb** [comment]
Your workflow seems very interesting, I will try it this week I and tell you how it went.

Curently Cursor is almost broken with the last update, is why I'm searching for a replacement. What I miss the most about  Cursor is the @ sign in to do a fuzzy-search of file in the middle of a sentence.

"check how @file1 works and try to replicate it in @file2 but this time using @apiBackendFile as you data source"

This way of prompting felt so natural and it gived me very amazing results. 

There is no dark magic to it, I imagined a plugin where I can do that and the plugin simply pastes the files at the bottom of the prompt, I can then copy and paste into any llm I want.

**Comment by Thomas-McKanna** [comment]
This one is complete @Antoine-lb.
