### ISSUE TITLE
Gitignored files and folders should be disabled from selection

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#2]
Paths specified in gitignore are not files we work on thus should be ignored doing parent selection.

![image](https://github.com/user-attachments/assets/d068c6da-72b6-4732-896e-9856ea3841cb)

**Comment by Thomas-McKanna** [comment]
Hmmmmm, this should be implemented. I wonder if you have some sort of special case I'm not covering. For example, I just tested this out by making a `test` folder with two subfolders `foo` and `node_modules`. Since `node_modules` is ignored, when I select `test`, only `foo` and its contents are selected:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/661b7b03-6fc6-44b5-b154-5399de5927b1">

I suppose what you want is the `.gitignore` inside the folder you are selecting (`web-extension`) to be used. Is this right? I believe I have the extension implemented to use the `.gitignore` file in the root of the workspace, but I need to double check.
