### ISSUE TITLE
Copy opened files

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#4]
To avoid need of installation of some separate extension it would be great to quickly copy to clipboard all open files. The overall format of copied text should be followed, which works great by the way. What do you think?

**Comment by Thomas-McKanna** [comment]
I like this as an additional feature that could be supported via a key-bind, but I don't want to change the ability to select files in the extension UI, as I find this to be useful in my workflow (I often have files open that I wouldn't want to be copied, or would be missing files I want to copy).

It could be supported by something like cmd + shift + c or something similar (customizable by user).

I do really like the idea - but just as an additional feature rather than changing existing copy functionality.

I'll try to implement this one soon - let me know if you have any further thoughts.
