### ISSUE TITLE
Newly created files within selected directories are not selected

### ISSUE THREAD

**Issue by robertpiosik** [Thomas-McKanna/Files2Prompt#5]
The extension should remember the previously selected parent directory so that newly added files are automatically included in subsequent copy operations.

This functionality, along with storing the state of the file tree for each copy action, could enable a much-needed feature: restoring tree states for backward/forward navigation.

In my eyes, this would make the extension complete.

**Comment by Thomas-McKanna** [comment]
Agreed - this should be fairly straightforward to implement.

To make sure I understand, tell me if this example is correct: Let's say we have a directory called `A` which contains files `B` and `C`. The user selects directory `A` causing files `B` and `C` to be copied when triggered. Now the user adds file `D` to directory `A`. Currently, file `D` would not be automatically selected in copy operations. But you are suggesting that with this issue, file `D` should automatically be selected since directory `A` is selected.

**Comment by Thomas-McKanna** [comment]
I implemented several of your suggestions. Can you please update and close the issues you think or done or comment those you think are not done?

**Comment by Thomas-McKanna** [comment]
Yeah it looks like you are right. It is close, but somehow the file watcher functionality (to auto-update the extension UI file tree when files are created/deleted) seems to not be working in the pushed version.

I will investigate and push a fix this weekend. If you manually refresh the file tree (cmd + R), newly added files should be selected, so you may begin to use this for now.

**Comment by Thomas-McKanna** [comment]
This should be implemented with the latest update.
